### PR TITLE
Separate modules and guides

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Nowosad** [comment]
Cool. There is a typo in Roger's surname though.

**Comment by Robinlovelace** [comment]
Well spotted @Nowosad, thanks for the review, should be fixed now.

**Comment by Nowosad** [comment]
@Robinlovelace merge?

**Comment by Robinlovelace** [comment]
Cheers for the reminder @Nowosad. Suggest we review (and merge) each other's PRs. Happy NY btw :tada:

**Comment by Nowosad** [comment]
Happy New Year, @Robinlovelace !

**Pull request merged**
